FROM mobingi/ubuntu-apache2-php5
RUN mkdir /var/www/html/thaiSilk
RUN mkdir /var/www/html/thaiSilk/appointment
COPY webroot/index.html /var/www/html
COPY webroot/thaiSilk/appointment/ /var/www/html/thaiSilk/appointment/
WORKDIR /var/www/html/
